### ISSUE TITLE
Big files not working!

### ISSUE THREAD

**Issue by mastudiosfin** [tom-weiland/csharp-game-launcher#1]
If you have a large game file, you won't be able to use it because Google Drive's virus scan doesn't automatically scan the file for viruses and therefore the direct link won't work!

**Comment by tom-weiland** [comment]
Yeah, Google Drive is meant to just be used as an example. If you have a larger file, you can try others like DropBox, OneDrive, etc. but I believe most of these have limits on how often files can be downloaded, so in production you'd want to find a proper way to host files.
