### ISSUE TITLE
Cheating Cheating/Using plug-ins

### ISSUE THREAD

**Issue by Hamidzai456hzj** [tom-weiland/csharp-game-launcher#10]

**Comment by tom-weiland** [comment]
?

**Comment by Hamidzai456hzj** [comment]
> _هیچ توضیحی ارائه نشده است._

1. ``

**Comment by tom-weiland** [comment]
Closing this do to blank/empty messages. If you have an actual issue to report, please describe it properly (in English). Otherwise, please refrain from creating new issues.
