### ISSUE TITLE
1. Code "CONFETTI9" for Speed Burst 🚀 2. Code "THUNDER7" for Lightning Blitz ⚡ 3. Code "RAPID11" for Quick Steps 🏃‍♀️

### ISSUE THREAD

**Issue by Hamidzai456hzj** [tom-weiland/csharp-game-launcher#11]

**Comment by tom-weiland** [comment]
Closing this do to blank/empty messages. If you have an actual issue to report, please describe it properly (in English). Otherwise, please refrain from creating new issues.
