### ISSUE TITLE
Cannot download files!

### ISSUE THREAD

**Issue by Satindar31** [tom-weiland/csharp-game-launcher#2]
i followed the tutorial and made changes in the code now when I run it it shows this message

![image](https://user-images.githubusercontent.com/73517520/121497094-b58e3400-c9f8-11eb-9635-db9800b34d0b.png)

**Comment by tom-weiland** [comment]
Was it working before you made those changes? Also, take a look at the pinned comment on the video.

**Comment by extremepro999** [comment]
> Was it working before you made those changes? Also, take a look at the pinned comment on the video.

by changes I meant putting my download link instead of yours

**Comment by Satindar31** [comment]
> Was it working before you made those changes? Also, take a look at the pinned comment on the video.

Thanks i found the issue it was the virus scan thing i am now using media fire and it works like a charm
