### ISSUE TITLE
unable to run.

### ISSUE THREAD

**Issue by oxmc** [tom-weiland/csharp-game-launcher#3]
I don't know how to build it, or run it.

**Comment by tom-weiland** [comment]
You should be able to build/run it just like a C# console application...

If you don't know how to do that (hit F5, click the green play button at the top of your Visual Studio window, or right click the project in the solution explorer and hit "Build"), then that's something you should have googled or asked in the YouTube comments/on Discord. GitHub issues are normally meant for when you have a problem specifically with the actual project.
