### ISSUE TITLE
Error finishing download on the built version on the launcher

### ISSUE THREAD

**Issue by LCJE** [tom-weiland/csharp-game-launcher#4]
It works inside visual studio but when i build it then try i get this error
![image](https://user-images.githubusercontent.com/59238052/127261272-90597b08-5d94-4da7-ac7f-2f1a1edff035.png)

**Comment by tom-weiland** [comment]
Well considering it can't find the file, check all your file paths? Make sure they are all correct even when you build it, although I'm really not sure why it would work in Visual Studio but not as a build—especially if you haven't made any of your own changes/additions to the code...

Assuming you followed along with the tutorial, you could also try downloading the entire project from GitHub and running that (don't forget to change file paths and download links). I'm not sure if a difference in the code would produce the behavior you're seeing, but it might still be good to rule out.

**Comment by LCJE** [comment]
I found that it works when I run it as an administrator, the reason why It only works when I run it as administrator is because ive put the launcher in the ProgramFiles folder. I'll just make it run as administrator by defualt. Thanks for reply though the tutorial was very useful.
