### ISSUE TITLE
Embedded Launcher

### ISSUE THREAD

**Issue by mhadji05** [tom-weiland/csharp-game-launcher#5]
Can you create an embedded launcher into the game?

I mean you are using 2 executables to do the update. Can you do this into the game?

**Comment by tom-weiland** [comment]
You could have the game check for its own updates, but it wouldn't be able to update itself. Applications can't really replace their own files while they're running.

**Comment by mhadji05** [comment]
I don't know how to run this project. I am Unity developer. Do you have similar project created on Unity?

**Comment by tom-weiland** [comment]
> I don't know how to run this project.

You press the play button at the top of your Visual Studio window, or you press F5.

> Do you have similar project created on Unity?

No, but you could probably take all the code related to downloading and replacing files and put it into a Unity project. It might need some tweaking but should work for the most part.

**Comment by mhadji05** [comment]
Hello I have already open the project, update the Google Drive Links for Build.zip and Version.txt files but I get this error.
Also why is it necessary to have Version.txt file in the GameLauncher folder?

![Untitled](https://user-images.githubusercontent.com/22151801/129598815-28bade0d-8010-4373-8dc2-b5f4631702ad.png)

Should not check the version of .exe if it is the same as Version.txt in Drive?
If I understand correctly now is checking if the version of Version.txt in GameLauncher folder is the same as that of Version.txt in Drive?

**Comment by tom-weiland** [comment]
> Hello I have already open the project, update the Google Drive Links for Build.zip and Version.txt files but I get this error.

Try using Dropbox or OneDrive to store the game files instead, a lot of people have had issues when using Google Drive.

> Should not check the version of .exe if it is the same as Version.txt in Drive?

You could probably do that if you'd prefer it that way.
> If I understand correctly now is checking if the version of Version.txt in GameLauncher folder is the same as that of Version.txt in Drive?

Yes.

If you have any further questions or errors, join the [Discord server](https://discord.gg/tomweiland) and ask there. GitHub's issues feature is mainly meant for discussing and solving bugs with the actual repo itself, more general questions are better (and more quickly) answered on Discord.

**Comment by mhadji05** [comment]
Hello.

I have already tried Dropbox and OneDrive to store the game files but always i have the error I mention in the previous comment.
Please let me know

**Comment by tom-weiland** [comment]
Did you happen to zip the zip file with a third party application like Winrar or 7zip? The `ZipFile.ExtractToDirectory` method is intended for unzipping files that have been zipped the "regular" Windows way.

If that's not it, there's nothing else I can do to help you without you narrowing down what the problem is. Try manually unzipping the downloaded file and see if that works—if it doesn't then something is wrong with the file being downloaded.
